package main

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// ProjectDir replicates Claude Code's Cx() transform for a workspace path:
//  1. Replace each character that is NOT [a-zA-Z0-9] with '-'
//  2. If the result is <= 200 chars, return it
//  3. Otherwise, compute Java's hashCode of the ORIGINAL path, convert to
//     base36, and append it as a suffix to the result truncated at 200 chars
func ProjectDir(workspace string) string {
	var b strings.Builder
	b.Grow(len(workspace))
	for _, c := range workspace {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') {
			b.WriteRune(c)
		} else {
			b.WriteByte('-')
		}
	}
	sanitised := b.String()

	if len(sanitised) <= 200 {
		return sanitised
	}

	hash := javaHashCode(workspace)
	suffix := int32ToBase36(hash)
	return sanitised[:200] + suffix
}

// ConfigHome returns the mittens configuration directory.
// It honours MITTENS_HOME; otherwise defaults to ~/.mittens.
func ConfigHome() string {
	if v := os.Getenv("MITTENS_HOME"); v != "" {
		return v
	}
	home, err := os.UserHomeDir()
	if err != nil {
		// Fallback; should never happen in practice.
		return filepath.Join("/tmp", ".mittens")
	}
	return filepath.Join(home, ".mittens")
}

// LoadProjectConfig reads the per-project config file and returns the stored
// flags, one per line. Blank lines and lines starting with '#' are skipped.
func LoadProjectConfig(workspace string) ([]string, error) {
	path := projectConfigPath(workspace)
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading config %s: %w", path, err)
	}

	var flags []string
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// Split each line into words so "--go 1.24" becomes ["--go", "1.24"].
		flags = append(flags, strings.Fields(line)...)
	}
	return flags, nil
}

// SaveProjectConfig writes flags to the per-project config file (one per line),
// creating directories as needed.
func SaveProjectConfig(workspace string, lines []string) error {
	path := projectConfigPath(workspace)
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating config dir %s: %w", dir, err)
	}

	var b strings.Builder
	b.WriteString("# mittens project config — one flag per line\n")
	b.WriteString("# Generated by mittens; feel free to edit.\n")
	for _, l := range lines {
		b.WriteString(l)
		b.WriteByte('\n')
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// RoleConfig holds per-provider role overrides for a project.
type RoleConfig struct {
	Roles map[string]map[string]RolePreset `json:"roles"`
}

// LoadRoleConfig reads role overrides for the given workspace.
func LoadRoleConfig(workspace string) (*RoleConfig, error) {
	path := roleConfigPath(workspace)
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return &RoleConfig{Roles: map[string]map[string]RolePreset{}}, nil
		}
		return nil, fmt.Errorf("reading role config %s: %w", path, err)
	}

	var cfg RoleConfig
	if err := json.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing role config %s: %w", path, err)
	}
	if cfg.Roles == nil {
		cfg.Roles = map[string]map[string]RolePreset{}
	}
	return &cfg, nil
}

// SaveRoleConfig persists role overrides for the given workspace.
func SaveRoleConfig(workspace string, cfg *RoleConfig) error {
	if cfg == nil {
		cfg = &RoleConfig{Roles: map[string]map[string]RolePreset{}}
	}
	if cfg.Roles == nil {
		cfg.Roles = map[string]map[string]RolePreset{}
	}

	path := roleConfigPath(workspace)
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating role config dir %s: %w", dir, err)
	}

	payload, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}

	return os.WriteFile(path, append(payload, '\n'), 0o644)
}

// loadProjectConfigRaw reads the per-project config file and returns the
// non-comment, non-blank lines as-is (without splitting into words). This is
// used for display and for edit-mode categorisation where line structure matters
// (e.g. "--go 1.24" must stay as one entry, not become ["--go", "1.24"]).
func loadProjectConfigRaw(workspace string) ([]string, error) {
	path := projectConfigPath(workspace)
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading config %s: %w", path, err)
	}

	var lines []string
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		lines = append(lines, line)
	}
	return lines, nil
}

// projectConfigPath returns the full path to the config file for the given
// workspace directory.
func projectConfigPath(workspace string) string {
	return filepath.Join(ConfigHome(), "projects", ProjectDir(workspace), "config")
}

func roleConfigPath(workspace string) string {
	return filepath.Join(ConfigHome(), "projects", ProjectDir(workspace), "roles.json")
}

// javaHashCode computes the hash using Java's String.hashCode() algorithm:
//
//	hash = 0; for each char: hash = hash*31 + char
//
// All arithmetic uses int32 wrapping semantics.
func javaHashCode(s string) int32 {
	var h int32
	for _, c := range s {
		h = h*31 + int32(c)
	}
	return h
}

// int32ToBase36 converts a signed int32 to a base-36 string (like Java's
// Integer.toString(n, 36)). Negative values get a leading '-'.
func int32ToBase36(n int32) string {
	if n == 0 {
		return "0"
	}
	negative := n < 0
	// Use int64 to safely handle math.MinInt32
	v := int64(n)
	if negative {
		v = -v
	}
	// Edge case: int32 min value overflows when negated in int32,
	// but int64 handles it fine.
	if v < 0 {
		// Only happens for math.MinInt32
		v = int64(math.MaxInt32) + 1
	}
	s := strconv.FormatInt(v, 36)
	if negative {
		return "-" + s
	}
	return s
}
